export const ADD_CART_REQUEST="ADD_CART_REQUEST";
export const ADD_CART_SUCCESS="ADD_CART_SUCCESS";
export const ADD_CART_FAILURE="ADD_CART_FAILURE";



export const ADD_PRODUCT_IN_CART_REQUEST="ADD_PRODUCT_IN_CART_REQUEST";
export const ADD_PRODUCT_IN_CART_SUCCESS="ADD_PRODUCT_IN_CART_SUCCESS";
export const ADD_PRODUCT_IN_CART_FAILURE="ADD_PRODUCT_IN_CART_FAILURE";


export const REMOVE_PRODUCT_IN_CART_REQUEST="REMOVE_PRODUCT_IN_CART_REQUEST";
export const REMOVE_PRODUCT_IN_CART_SUCCESS="REMOVE_PRODUCT_IN_CART_SUCCESS";
export const REMOVE_PRODUCT_IN_CART_FAILURE="REMOVE_PRODUCT_IN_CART_FAILURE";