export const ALL_PRODUCT_FETCH_REQUEST="ALL_PRODUCT_FETCH_REQUEST";
export const ALL_PRODUCT_FETCH_SUCCESS="ALL_PRODUCT_FETCH_SUCCESS";
export const ALL_PRODUCT_FETCH_FAILURE="ALL_PRODUCT_FETCH_FAILURE";


export const ALL_SINGLE_PRODUCT_REQUEST="ALL_SINGLE_PRODUCT_REQUEST";
export const ALL_SINGLE_PRODUCT_SUCCESS="ALL_SINGLE_PRODUCT_SUCCESS";
export const ALL_SINGLE_PRODUCT_FAILURE="ALL_SINGLE_PRODUCT__FAILURE";

