export const MEN_PRODUCT_FETCH_REQUEST="MEN_PRODUCT_FETCH_REQUEST";
export const MEN_PRODUCT_FETCH_SUCCESS="MEN_PRODUCT_FETCH_SUCCESS";
export const MEN_PRODUCT_FETCH_FAILURE="MEN_PRODUCT_FETCH_FAILURE";


export const MENS_SINGLE_PRODUCT_REQUEST="MENS_SINGLE_PRODUCT_REQUEST";
export const MENS_SINGLE_PRODUCT_SUCCESS="MENS_SINGLE_PRODUCT_SUCCESS";
export const MENS_SINGLE_PRODUCT_FAILURE="MENS_SINGLE_PRODUCT__FAILURE";

