export const WOMENS_PRODUCT_FETCH_REQUEST="WOMENS_PRODUCT_FETCH_REQUEST";
export const WOMENS_PRODUCT_FETCH_SUCCESS="WOMENS_PRODUCT_FETCH_SUCCESS";
export const WOMENS_PRODUCT_FETCH_FAILURE="WOMENS_PRODUCT_FETCH_FAILURE";


export const WOMENS_SINGLE_PRODUCT_REQUEST="WOMENS_SINGLE_PRODUCT_REQUEST";
export const WOMENS_SINGLE_PRODUCT_SUCCESS="WOMENS_SINGLE_PRODUCT_SUCCESS";
export const WOMENS_SINGLE_PRODUCT_FAILURE="WOMENS_SINGLE_PRODUCT__FAILURE";


